# Docker compose for development, to spin up agency + indy ledger + postgres wallets db within this repo
# Note ensure the following env params are set
# WALLET_DB_HOST=wallets-db
version: '3.5'

networks:
    agency-network:
      name: agency-network
      driver: bridge
      ipam:
        driver: default
        config:
          -
            subnet: 10.0.0.0/24

services:
  multitenant:
    image: bcgovimages/aries-cloudagent:py36-1.15-1_0.6.0
    container_name: multitenant
    networks:
      - agency-network
    ports:
      - "3020:3020"
      - "3021:3021"
    expose: 
      - "3020"
      - "3021"
    volumes:
      - ./resources/:/resources
    command: start
        --inbound-transport http '0.0.0.0' 3020
        --outbound-transport http
        --endpoint http://multitenant:3020
        --wallet-type 'indy'
        --wallet-name 'multitenant'
        --wallet-key 'multitenant_key'
        --wallet-storage-type 'postgres_storage'
        --wallet-storage-config '{"url":"wallets-db:5432","wallet_scheme":"MultiWalletSingleTable"}'
        --wallet-storage-creds '{"account":"postgres","password":"dbpass","admin_account":"postgres","admin_password":"dbpass"}'
        --seed '000000000000000000000000Steward1'
        --admin '0.0.0.0' 3021
        --admin-api-key 'adminApiKey'
        --label multitenant
        --webhook-url http://aries-guardianship-agency:3010/v1/controller/multitenant
        --log-level debug
        --wallet-local-did
        --auto-provision
        --multitenant
        --multitenant-admin
        --jwt-secret jwtSecret
        --seed 000000000000000000000000Steward1
        --genesis-url http://aries-guardianship-agency:3010/genesis-file

