# Docker compose to spin up agency to interact with a local kiva-network from the protocol repo
# Note ensure the following env params are set:
# WALLET_DB_HOST=protocol-identity-wallets-db
# NETWORK_NAME=kiva-network
#
version: '3.5'

networks:
  kiva-network:
    external: true

services:
  guardianship-agency:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    command: npm run start:debug
    image: guardianship-agency
    container_name: guardianship-agency
    working_dir: /www
    ports:
      - "3010:3010"
    expose: 
      - "3010"
    volumes:
      - ./:/www
      - //var/run/docker.sock:/var/run/docker.sock
    networks:
      - kiva-network
    tty: true
