# Docker compose for production/ci to spin up agency + indy ledger + postgres wallets db within this repo
# Note ensure the following env params are set
# WALLET_DB_HOST=wallets-db
version: '3.5'

networks:
    agency-network:
      external: true

services:
  guardianship-agency:
    build:
      context: ./
      dockerfile: docker/Dockerfile.production
    env_file:
      - .env
    image: guardianship-agency
    container_name: guardianship-agency
    working_dir: /www
    ports:
      - "3010:3010"
    expose: 
      - "3010"
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    networks:
      - agency-network
    tty: true
