# Docker compose for production/ci to spin up agency + indy ledger + postgres wallets db within this repo
# Note ensure the following env params are set
# WALLET_DB_HOST=wallets-db
version: '3.5'

networks:
    agency-network:
      name: agency-network
      driver: bridge
      ipam:
        driver: default
        config:
          -
            subnet: 10.0.0.0/24

services:
      # indy pool needs a static ip configured in the pool_transactions_genesis so need to start it first
  indy-pool:
    build:
      context: .
      dockerfile: docker/indy-pool.dockerfile
      args:
        pool_ip: '10.0.0.2'
    image: indy-pool
    container_name: indy-pool
    working_dir: /home/indy
    ports:
      - "9701:9701"
      - "9702:9702"
      - "9703:9703"
      - "9704:9704"
      - "9705:9705"
      - "9706:9706"
      - "9707:9707"
      - "9708:9708"
    networks:
      agency-network:
        ipv4_address: 10.0.0.2

  wallets-db:
    image: postgres:11
    container_name: wallets-db
    command: postgres
    env_file:
      - .env
    volumes:
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - agency-network
    depends_on:
      - indy-pool
    tty: true

  aries-guardianship-agency:
    build:
      context: ./
      dockerfile: docker/Dockerfile.production
    env_file:
      - .env
    image: aries-guardianship-agency
    container_name: aries-guardianship-agency
    working_dir: /www
    ports:
      - "3010:3010"
    expose: 
      - "3010"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - agency-network
    depends_on:
      - indy-pool
    tty: true
    privileged: true

  tails-server:
    image: kivaprotocol/tails-server:latest
    container_name: tails-server
    ports:
      - 6543:6543
    networks:
      - agency-network
    depends_on:
      - indy-pool
    env_file:
      - .env
    command: >
      tails-server
        --host 0.0.0.0
        --port 6543
        --storage-path /tmp/tails-files
        --log-level INFO

  multitenant:
    image: bcgovimages/aries-cloudagent:py36-1.15-1_0.6.0
    container_name: multitenant
    networks:
      - agency-network
    depends_on:
      - indy-pool
      - wallets-db
    ports:
      - "3020:3020"
      - "3021:3021"
    expose: 
      - "3020"
      - "3021"
    env_file:
      - .env
    volumes:
      - ./resources/:/home/indy/resources
    command: start
      --inbound-transport http '0.0.0.0' 3020
