replicaCount: 2

image:
  repository: kivaprotocol/aries-guardianship-agency
  tag: latest
  pullPolicy: Always
  imagePullSecrets:
    - name: "regcred"

nameOverride: "aries-guardianship-agency"
fullnameOverride: "aries-guardianship-agency"
secrets: "aries-guardianship-agency-secrets"

strategy:
  type: "RollingUpdate"

service:
  type: ClusterIP
  port: 3010
  containerPort: 8080
  targetPort: 8080
  portName: http

resources:
  limits:
    cpu: 1100m
    memory: 607164212
  requests:
    cpu: 1100m
    memory: 607164212

readiness:
  initialDelaySeconds: 20
  timeoutSeconds: 1
  path: /healthz

liveness:
  initialDelaySeconds: 20
  timeoutSeconds: 10
  path: /healthz

ingress:
  enabled: false # set to true if component needs ingress
  host: "replaceme.replacethisdomain"
  class: nginx-ingress-external
  secret: "replaceme-tls"

volume:
  enabled: true
  name: agency-data
  claim: agency-vol
  size: 8Gi
  mountPath: "/tmp/diskcache"

securityContext:
  enabled: true
  user: 102 # default user ID for the app user
  fsGroup: 102

# By default services should disable this option as it is used to give the pod
# elevated k8s privileges
serviceAccount:
  enabled: true
  name: agency-kubectl

# Uncomment below to allocate pods to a specific node type.
#
#tolerations:
#  - effect: NoSchedule
#    key: crypto
#    operator: Equal
#    value: "true"
#
#nodeSelector:
#    dedicated: crypto
#
#affinity: {}
